grow_version: ">=0.6.4"
home: /content/amp-dev/index.html

localization:
  root_path: /{locale}/
  default_locale: en
  locales:
  - en
  - fr
  # - ar
  # - es
  # - it
  # - id
  # - ja
  # - ko
  # - pt_BR
  # - ru
  # - tr
  # - zh_CN

markdown:
  extensions:
  - kind: sourcecode
    classes: True
    class_name: ad-m-code-snippet
  - kind: markdown.extensions.codehilite
    classes: True
    class_name: ad-m-code-snippet

ext:
- extensions.inline_text_assets.InlineTextAssetsExtension:
    bundles:
        - name: 'styles'
          method: 'addCssFile'
        - name: 'icons'
          method: 'useIcon'
- extensions.shortcodes.ShortcodesExtension
- extensions.amp_dependency_injector.AmpDependencyInjectorExtension
